[target.aarch64-unknown-linux-gnu]
image = "aarch64-linux-gnu"

[target.x86_64-unknown-linux-gnu]
image = "x86_64-linux-gnu"

[target.x86_64-unknown-linux-musl]
pre-build = [
  "apt update && apt install --assume-yes clang wget unzip && wget https://github.com/protocolbuffers/protobuf/releases/download/v21.10/protoc-21.10-linux-x86_64.zip && unzip protoc-21.10-linux-x86_64.zip -d .local && mv \"$(pwd)/.local/bin/protoc\" /bin/ && mv \"$(pwd)/.local/include/google\" /usr/include/",
]
