[package]
name = "xlineapi"
version = "0.1.0"
edition = "2021"
authors = ["DatenLord <dev@datenlord.io>"]
description = "Xline RPC API"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/datenlord/Xline/tree/master/xlineapi"
categories = ["RPC"]
keywords = ["RPC", "Interfaces"]

[dependencies]
tonic = "0.7.2"
prost = "0.10.3"
serde = { version = "1.0.137", features = ["derive"] }
etcd-client = "0.10.1"

[build-dependencies]
tonic-build = "0.7.2"
