[package]
name = "xline-discovery"
version = "0.1.0"
edition = "2021"

[dependencies]
xline-client = { path = "../xline-client" }
thiserror = "1.0.44"
serde = { version = "1", features = ["derive"] }
bincode = "1.3.3"
